### PR TITLE
Refactor Tesla boost

### PR DESCRIPTION
**Pull request by GraionDilach**
I'd suggest you to squash the first commit and only keep the one with the new sound. Keep in mind that this implementation depends upon both your fix regarding upgradable Armaments and OpenRA#8558 now.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Ah yeah, it'll also need rebase and other nits, but this should give you an idea how to carry it on.

**Comment by matija-hustic** [comment]
Thanks man, I'll pull this as soon as I have access to my computer and of course credit you fully for it. You tried it out? It works normally?

**Comment by GraionDilach** [comment]
Bah, just squash the first commit entirely into your own initial one. You did a great work, I'm just a perfectionist - with a lot of quirks and nitpicking due to trying to think ahead. :smile: 

I didn't try out the Armament granting part because I'm not a fan of merging branches back and forth. I only did a merge with my 8558 PR merged in and that granted the RequiresPower part, so it all comes down to the dependencies.

And really sorry for the flak about this PR anyway.

**Comment by GraionDilach** [comment]
I also noticed this was the sole TS format SHP in the bits folder so I couldn't resist converting it to SHP(TD) format.

**Comment by matija-hustic** [comment]
Thanks @GraionDilach, I've included all your contributions in the final code!

**Comment by GraionDilach** [comment]
The source of the sound should probably be mentioned in it's commit though to prevent confusion about it's origins in the future.

**Comment by matija-hustic** [comment]
Done :+1:

**Pull request closed without merging**
